version: '3'

services:
  mysql:
      container_name: mysql
      image: mysql:8.0.1
      deploy:
        replicas: 1
        placement:
          constraints:
            - node.hostname == if-mysql
      volumes:
        - db_data:/var/lib/mysql
        - ./docker/data:/docker-entrypoint-initdb.d
      restart: always
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=${IF_DB_ROOT_PASS}
        - MYSQL_USER=ideafoundry
        - MYSQL_DATABASE=ideafoundrybi
        - MYSQL_PASSWORD=${IF_DB_PASSWORD}
volumes:
  db_data: