version: '3'

services:
  processorderemail:
    depends_on:
      - mailsource      
      - mysql
    container_name: processorderemail
    image: ideafoundry/occasion-order-email-processor-service:1.0.0
    ports:
      - "8181:8181"
    environment:
      - IF_AIRTABLE_CREDS=${IF_AIRTABLE_CREDS}
      - HOST_IP=${HOST_IP}
      - IF_DB_PASSWORD=${IF_DB_PASSWORD}
      - IF_DB_PORT=${IF_DB_PORT}
      - IF_DB_USERNAME=${IF_DB_USERNAME}
      - IF_OCCASION_CREDS=${IF_OCCASION_CREDS}
  createperson:
    depends_on:
      - processorderemail      
    container_name: createperson
    image: ideafoundry/create-airtable-person-service:1.0.0
    ports:
      - "8182:8182"
    environment:
      - IF_AIRTABLE_CREDS=${IF_AIRTABLE_CREDS}
      - HOST_IP=${HOST_IP}
      - IF_DB_PASSWORD=${IF_DB_PASSWORD}
      - IF_DB_PORT=${IF_DB_PORT}
      - IF_DB_USERNAME=${IF_DB_USERNAME}
  createorder:
    depends_on:
      - createperson
    container_name: createorder
    image: ideafoundry/create-airtable-order-service:1.0.0
    ports:
      - "8183:8183"
    environment:
      - IF_AIRTABLE_CREDS=${IF_AIRTABLE_CREDS}
      - HOST_IP=${HOST_IP}
      - IF_DB_PASSWORD=${IF_DB_PASSWORD}
      - IF_DB_PORT=${IF_DB_PORT}
      - IF_DB_USERNAME=${IF_DB_USERNAME}
  createquestion:
    depends_on:
      - createorder
    container_name: createquestion
    image: ideafoundry/create-airtable-question-service:1.0.0
    ports:
      - "8184:8184"
    environment:
    - IF_AIRTABLE_CREDS=${IF_AIRTABLE_CREDS}
    - HOST_IP=${HOST_IP}
    - IF_DB_PASSWORD=${IF_DB_PASSWORD}
    - IF_DB_PORT=${IF_DB_PORT}
    - IF_DB_USERNAME=${IF_DB_USERNAME}
  mailsource:
    depends_on:
      - kafka
    container_name: mailsource
    image: ideafoundry/mail-source:1.2.0
    ports:
      - "8185:8185"
    environment:
      - IF_EMAIL_ID=${IF_EMAIL_ID}
      - IF_EMAIL_CREDS=${IF_EMAIL_CREDS}
      - HOST_IP=${HOST_IP}
  mysql:
    container_name: mysql
    image: mysql:8.0.1
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/data:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${IF_DB_ROOT_PASS}
      MYSQL_USER: ideafoundry
      MYSQL_PASSWORD: ${IF_DB_PASSWORD}
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    depends_on:
      - zookeeper
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
    db_data: