version: '3'

services:
  # processorderemail:
  #   depends_on:
  #     - kafka
  #   container_name: processorderemail
  #   image: ideafoundry/processorderemail
  #   ports:
  #     - "8181:8181"
  #   environment:
  #     - if.occasion.creds
  # createperson:
  #   depends_on:
  #     - mysql
  #   container_name: createperson
  #   image: ideafoundry/createperson
  #   ports:
  #     - "8182:8182"
  # createorder:
  #   depends_on:
  #     - mysql
  #   container_name: createorder
  #   image: ideafoundry/createorder
  #   ports:
  #     - "8183:8183"
  # createquestion:
  #   depends_on:
  #     - mysql
  #   container_name: createquestion
  #   image: ideafoundry/createquestion
  #   ports:
  #     - "8184:8184"
  # mailstarter:
  #   depends_on:
  #     - kafka
  #   container_name: mailstarter
  #   image: ideafoundry/mailstarter
  #   ports:
  #     - "8185:8185"
  mysql:
    container_name: mysql
    image: mysql:8.0.1
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/data:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${IF_DB_ROOT_PASS}
      MYSQL_DATABASE: ideafoundrybi
      MYSQL_USER: ideafoundry
      MYSQL_PASSWORD: ${IF_DB_PASSWORD}
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
    db_data: