version: '3'

services:
  reconcileorders:
    image: ideafoundry/reconcile-order:1.2.0
    depends_on:
      - kafka
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - engine.labels.node.type==1gb
    environment:
      - DB_HOST=${DB_HOST}
      - IF_DB_PORT=${IF_DB_PORT}
      - IF_DB_USERNAME=${IF_DB_USERNAME}
      - IF_DB_PASSWORD=${IF_DB_PASSWORD}
      - KAFKA_HOST=${KAFKA_HOST}
      - ZOOKEEPER_HOST=${ZOOKEEPER_HOST}