version: '3'

services:
  personsink:
    depends_on:
      - kafka
      - mysql
    image: ideafoundry/create-airtable-person-service:1.26.11-SNAPSHOT
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: ${INSTANCE_COUNT}
      placement:
        constraints:
          - engine.labels.node.type==createperson
    environment:
      - IF_OCCASION_RECONCILE=${IF_OCCASION_RECONCILE}
      - MAX_CREATEPERSON_INSTANCE_COUNT=${MAX_CREATEPERSON_INSTANCE_COUNT}
      - DB_HOST=${DB_HOST}
      - IF_DB_PORT=${IF_DB_PORT}
      - IF_DB_USERNAME=${IF_DB_USERNAME}
      - IF_DB_PASSWORD=${IF_DB_PASSWORD}
      - KAFKA_HOST=${KAFKA_HOST}
      - ZOOKEEPER_HOST=${ZOOKEEPER_HOST}