version: '3'

services:
  dataexport:
    depends_on:
      - personsink
      - kafka
      - mockoccasionapi
    image: ideafoundry/occasion-legacy-data-export-service:1.29.2-SNAPSHOT
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - engine.labels.node.type==1gb
    environment:
      - OKHTTP_CLIENT_TIMEOUT_SECONDS=${OKHTTP_CLIENT_TIMEOUT_SECONDS}
      - OCCASION_EXPORT_STARTING_PAGE_NUM=${OCCASION_EXPORT_STARTING_PAGE_NUM}
      - KAFKA_HOST=${KAFKA_HOST}
      - ZOOKEEPER_HOST=${ZOOKEEPER_HOST}
      - IF_OCCASION_CREDS=${IF_OCCASION_CREDS}
      - IF_OCCASION_EXPORT_URL=${IF_OCCASION_EXPORT_URL}
      - IF_OCCASION_RECONCILE=${IF_OCCASION_RECONCILE}