version: '3'

services:
  mockapi:
    image: ideafoundry/mock-occasion-api:2.4.3
    depends_on:
      - kafka
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints:
          - engine.labels.node.type==512mb